---
- name: Deploy FPL Insights App
  hosts: fpl_server
  become: yes
  connection: local  # <-- This line enables local execution
  vars_files:
    - ../vault.yml  # adjust path if needed

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install prerequisites (curl and pip)
      apt:
        name:
          - curl
          - python3-pip
        state: present

    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Install Docker dependencies
      apt:
        name:
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update APT after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine and Plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        state: present

    - name: Ensure Docker Python SDK for Ansible modules is installed
      pip:
        name: docker
        executable: pip3

    - name: Ensure containerd service is running
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull FPL Insights Docker image
      community.docker.docker_image:
        name: ringsfrings/fpl-insights-app
        tag: latest
        source: pull

    - name: Stop and remove existing container (if any)
      community.docker.docker_container:
        name: fpl_app
        state: absent
        force_kill: true
        container_default_behavior: no_defaults

    - name: Run the new container
      community.docker.docker_container:
        name: fpl_app
        image: ringsfrings/fpl-insights-app:latest
        state: started
        ports:
          - "5000:5000"
        restart_policy: always
        container_default_behavior: no_defaults
