name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fpl/requirements.txt

      - name: Run Bandit SAST scan
        run: bandit -r fpl/

      - name: Build Docker image
        run: docker build -t ringsfrings/fpl-insights-app:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ringsfrings/fpl-insights-app:latest
          format: table

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push yourdockeruser/fpl-insights-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-scan
    steps:
      - name: SSH and deploy via Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbooks/deploy.yml
          directory: ./
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: --ask-vault-pass