name: CI/CD Pipeline with DevSecOps

on:
  push:
    branches: ["main"]

jobs:
  scan:
    name: DevSecOps Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Checkov
        run: pip install checkov

      - name: Scan Ansible playbooks with Checkov
        run: checkov -d ansible/playbooks/

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Scan DockerHub image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL ringsfrings/fpl-insights-app:latest

  deploy:
    name: Deploy with Ansible to Node-02
    runs-on: self-hosted
    needs: scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write vault password
        run: echo "${{ secrets.VAULT_PASSWORD }}" > ~/.vault_pass.txt

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbooks/deploy.yml \
            -i ansible/inventory.ini \
            --vault-password-file ~/.vault_pass.txt
