name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fpl/requirements.txt

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest
          format: table

      - name: Push Docker image to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Write Ansible Vault password to file
        run: |
          echo "${{ secrets.VAULT_PASSWORD }}" > vault_pass.txt

      - name: Deploy with Ansible
        run: |
          ansible-playbook ansible/playbooks/deploy.yml \
            -i ansible/inventory.ini \
            --vault-password-file vault_pass.txt

        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
          ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean up vault password file
        run: rm -f vault_pass.txt
