name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fpl/requirements.txt
          pip install bandit

      - name: Run Bandit SAST scan
        run: bandit -r fpl/

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest
          format: table

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-scan
    steps:
      - name: SSH and deploy via Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbooks/deploy.yml
          directory: ./
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: --vault-password-file ~/.vault_pass.txt
