name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fpl-insights-app:latest

  deploy:
    runs-on: self-hosted  # 💥 THIS RUNS ON YOUR NODE-02
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible (if not already installed)
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Write vault password to file
        run: echo "${{ secrets.VAULT_PASSWORD }}" > ~/.vault_pass.txt

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbooks/deploy.yml \
            -i ansible/inventory.ini \
            --vault-password-file ~/.vault_pass.txt
